version: '3.9'

services:
  database:
    image: postgres:13.0
    container_name: pgsql
    restart: on-failure
    environment:
      POSTGRES_DB: 'todo'
      POSTGRES_USER: 'user_admin'
      POSTGRES_PASSWORD: 'admin123'
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/migrations/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "5588:5432"
